// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import OnboardingController from "./onboarding_controller"
application.register("onboarding", OnboardingController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import DiagnosisController from "./diagnosis_controller"
application.register("diagnosis", DiagnosisController)

import LoadingController from "./loading_controller"
application.register("loading", LoadingController)
